"use client";

import { useEffect, useRef, useState } from "react";
import {
    ListMusic,
    Pause,
    Play,
    Repeat,
    Repeat1,
    Shuffle,
    SkipBack,
    SkipForward,
} from "lucide-react";
import type {
    MediaItem,
    MediaPlaybackState,
    PlaybackMode,
} from "@syncspace/shared";
import { IconButton } from "@/components/ui/IconButton";

interface VideoPlayerProps {
    media: MediaItem | null;
    playback: MediaPlaybackState | null;
    isHost: boolean;

    onPlay: () => void;
    onPause: () => void;
    onSeek: (position: number) => void;
    onEnded: () => void;

    onNext: () => void;
    onPrevious: () => void;
    onSetMode: (mode: PlaybackMode) => void;
}

interface YouTubePlayer {
    destroy: () => void;
    playVideo: () => void;
    pauseVideo: () => void;
    seekTo: (
        seconds: number,
        allowSeekAhead: boolean,
    ) => void;
    getCurrentTime: () => number;
    getPlayerState: () => number;
}

interface YouTubePlayerConstructor {
    new (
        element: HTMLElement,
        options: {
            videoId: string;
            playerVars?: {
                autoplay?: number;
                controls?: number;
                rel?: number;
                modestbranding?: number;
                playsinline?: number;
            };
            events?: {
                onReady?: () => void;
                onStateChange?: (event: {
                    data: number;
                }) => void;
            };
        },
    ): YouTubePlayer;
}

declare global {
    interface Window {
        YT?: {
            Player: YouTubePlayerConstructor;
            PlayerState: {
                ENDED: number;
                PLAYING: number;
                PAUSED: number;
                BUFFERING: number;
            };
        };
        onYouTubeIframeAPIReady?: () => void;
    }
}

const PLAYBACK_MODES: {
    value: PlaybackMode;
    label: string;
    Icon: typeof ListMusic;
}[] = [
    {
        value: "normal",
        label: "Normal",
        Icon: ListMusic,
    },
    {
        value: "repeat_one",
        label: "Repeat One",
        Icon: Repeat1,
    },
    {
        value: "repeat_queue",
        label: "Repeat Queue",
        Icon: Repeat,
    },
    {
        value: "shuffle",
        label: "Shuffle",
        Icon: Shuffle,
    },
];

const SYNC_INTERVAL_MS = 500;
const SEEK_THRESHOLD_SECONDS = 1.25;

type ClientSyncState =
    | "following"
    | "locally_paused"
    | "resyncing";

function extractYouTubeId(mediaId: string): string {
    return mediaId;
}

function isUsablePlayer(
    player: YouTubePlayer | null,
): player is YouTubePlayer {
    return (
        !!player &&
        typeof player.getCurrentTime === "function" &&
        typeof player.seekTo === "function" &&
        typeof player.playVideo === "function" &&
        typeof player.pauseVideo === "function"
    );
}

function getAuthoritativePosition(
    playback: MediaPlaybackState,
): number {
    if (!playback.isPlaying) {
        return Math.max(0, playback.position);
    }

    return Math.max(
        0,
        playback.position +
            Math.max(
                0,
                (Date.now() - playback.updatedAt) / 1000,
            ),
    );
}

export function VideoPlayer({
    media,
    playback,
    isHost,
    onPlay,
    onPause,
    onSeek,
    onEnded,
    onNext,
    onPrevious,
    onSetMode,
}: VideoPlayerProps) {
    const containerRef =
        useRef<HTMLDivElement | null>(null);

    const playerRef =
        useRef<YouTubePlayer | null>(null);

    /*
     * ALWAYS contains the latest server-authoritative state.
     *
     * This is deliberately independent from localPaused.
     */
    const playbackRef =
        useRef<MediaPlaybackState | null>(playback);

    const mediaRef =
        useRef<MediaItem | null>(media);

    const isHostRef =
        useRef(isHost);

    const onPlayRef =
        useRef(onPlay);

    const onPauseRef =
        useRef(onPause);

    const onSeekRef =
        useRef(onSeek);

    const onEndedRef =
        useRef(onEnded);

    /*
     * Participant-only local override.
     *
     * IMPORTANT:
     * localPaused means ONLY:
     *
     * "Keep my YouTube player paused."
     *
     * It does NOT mean:
     *
     * "Stop receiving/tracking server playback."
     */
    const localPausedRef =
        useRef(false);

    const clientSyncStateRef =
        useRef<ClientSyncState>("following");

    /*
     * Explicitly marks operations initiated by our code.
     *
     * This prevents YouTube callbacks generated by our own
     * pause/play/seek operations from being interpreted as
     * user commands.
     */
    const programmaticPauseRef =
        useRef(false);

    const programmaticPlayRef =
        useRef(false);

    const programmaticSeekRef =
        useRef(false);

    /*
     * Used only for a participant's local pause transition.
     */
    const localPauseTransitionRef =
        useRef(false);

    /*
     * Last position reported by the host seek detector.
     */
    const lastReportedSeekRef =
        useRef<number | null>(null);

    /*
     * Last authoritative position received from the server.
     *
     * This helps prevent the host seek detector from reporting
     * the same server-applied position back to the server.
     */
    const lastAuthoritativePositionRef =
        useRef<number | null>(null);

    /*
     * Protect callbacks from destroyed YouTube player instances.
     */
    const playerGenerationRef =
        useRef(0);

    const [apiReady, setApiReady] =
        useState(false);

    const [localPaused, setLocalPaused] =
        useState(false);

    useEffect(() => {
        playbackRef.current = playback;

        if (playback) {
            lastAuthoritativePositionRef.current =
                getAuthoritativePosition(playback);
        }
    }, [playback]);

    useEffect(() => {
        mediaRef.current = media;
    }, [media]);

    useEffect(() => {
        isHostRef.current = isHost;
    }, [isHost]);

    useEffect(() => {
        onPlayRef.current = onPlay;
    }, [onPlay]);

    useEffect(() => {
        onPauseRef.current = onPause;
    }, [onPause]);

    useEffect(() => {
        onSeekRef.current = onSeek;
    }, [onSeek]);

    useEffect(() => {
        onEndedRef.current = onEnded;
    }, [onEnded]);

    /*
     * ---------------------------------------------------------
     * LOCAL PLAYER COMMAND HELPERS
     * ---------------------------------------------------------
     */

    function pauseLocalPlayer(
        player: YouTubePlayer,
    ) {
        if (!isUsablePlayer(player)) {
            return;
        }

        programmaticPauseRef.current = true;

        try {
            player.pauseVideo();
        } catch {
            programmaticPauseRef.current = false;
        }
    }

    function playLocalPlayer(
        player: YouTubePlayer,
    ) {
        if (!isUsablePlayer(player)) {
            return;
        }

        programmaticPlayRef.current = true;

        try {
            player.playVideo();
        } catch {
            programmaticPlayRef.current = false;
        }
    }

    function seekLocalPlayer(
        player: YouTubePlayer,
        position: number,
    ) {
        if (!isUsablePlayer(player)) {
            return;
        }

        programmaticSeekRef.current = true;

        try {
            player.seekTo(
                Math.max(0, position),
                true,
            );
        } catch {
            programmaticSeekRef.current = false;
        }
    }

    /*
     * ---------------------------------------------------------
     * APPLY SERVER STATE
     * ---------------------------------------------------------
     *
     * This function is ONLY responsible for making the local
     * player follow authoritative server state.
     *
     * A participant-local pause is handled BEFORE this function
     * is called by the authoritative playback effect.
     */
    function applyAuthoritativeState(
        player: YouTubePlayer,
        targetPosition: number,
        shouldPlay: boolean,
        forceSeek: boolean,
    ) {
        if (!isUsablePlayer(player)) {
            return;
        }

        if (shouldPlay) {
            if (forceSeek) {
                seekLocalPlayer(
                    player,
                    targetPosition,
                );
            }

            playLocalPlayer(player);
            return;
        }

        /*
         * Server says PAUSED.
         *
         * Make sure the local player is paused first.
         */
        let playerState: number | null = null;

        try {
            playerState =
                player.getPlayerState();
        } catch {
            playerState = null;
        }

        if (
            playerState ===
            window.YT?.PlayerState.PAUSED
        ) {
            if (forceSeek) {
                seekLocalPlayer(
                    player,
                    targetPosition,
                );
            }

            return;
        }

        programmaticPauseRef.current = true;

        try {
            player.pauseVideo();
        } catch {
            programmaticPauseRef.current = false;
            return;
        }

        /*
         * Do not seek in the same tick as pause.
         *
         * The PAUSED callback will perform the deferred seek.
         */
        if (forceSeek) {
            localPauseTransitionRef.current = true;
        }
    }

    /*
     * ---------------------------------------------------------
     * YOUTUBE API
     * ---------------------------------------------------------
     */

    useEffect(() => {
        if (
            typeof window === "undefined"
        ) {
            return;
        }

        if (window.YT?.Player) {
            setApiReady(true);
            return;
        }

        const existingScript =
            document.querySelector(
                'script[src="https://www.youtube.com/iframe_api"]',
            );

        const previousCallback =
            window.onYouTubeIframeAPIReady;

        window.onYouTubeIframeAPIReady =
            () => {
                previousCallback?.();
                setApiReady(true);
            };

        if (!existingScript) {
            const script =
                document.createElement("script");

            script.src =
                "https://www.youtube.com/iframe_api";

            script.async = true;

            document.head.appendChild(script);
        }

        return () => {
            window.onYouTubeIframeAPIReady =
                previousCallback;
        };
    }, []);

    /*
     * ---------------------------------------------------------
     * CREATE / DESTROY YOUTUBE PLAYER
     * ---------------------------------------------------------
     */

    useEffect(() => {
        if (
            !apiReady ||
            !media ||
            !containerRef.current ||
            !window.YT?.Player
        ) {
            return;
        }

        const videoId =
            extractYouTubeId(media.mediaId);

        playerGenerationRef.current += 1;

        const generation =
            playerGenerationRef.current;

        const previousPlayer =
            playerRef.current;

        playerRef.current = null;

        if (previousPlayer) {
            try {
                previousPlayer.destroy();
            } catch {
                // Ignore cleanup errors.
            }
        }

        containerRef.current.innerHTML = "";

        const playerElement =
            document.createElement("div");

        playerElement.className =
            "h-full w-full";

        containerRef.current.appendChild(
            playerElement,
        );

        /*
         * New media = new local synchronization context.
         */
        clientSyncStateRef.current =
            "following";

        localPausedRef.current = false;
        localPauseTransitionRef.current = false;

        programmaticPauseRef.current = false;
        programmaticPlayRef.current = false;
        programmaticSeekRef.current = false;

        setLocalPaused(false);

        lastReportedSeekRef.current = null;

        lastAuthoritativePositionRef.current =
            playbackRef.current
                ? getAuthoritativePosition(
                      playbackRef.current,
                  )
                : null;

        const player =
            new window.YT.Player(
                playerElement,
                {
                    videoId,
                    playerVars: {
                        autoplay: 0,
                        controls: isHost ? 1 : 0,
                        rel: 0,
                        modestbranding: 1,
                        playsinline: 1,
                    },

                    events: {
                        onReady: () => {
                            if (
                                generation !==
                                playerGenerationRef.current
                            ) {
                                try {
                                    player.destroy();
                                } catch {
                                    // Ignore stale player cleanup.
                                }

                                return;
                            }

                            playerRef.current =
                                player;

                            const currentPlayback =
                                playbackRef.current;

                            if (
                                !currentPlayback ||
                                currentPlayback.mediaId !==
                                    videoId
                            ) {
                                return;
                            }

                            if (
                                !isUsablePlayer(
                                    player,
                                )
                            ) {
                                return;
                            }

                            const targetPosition =
                                getAuthoritativePosition(
                                    currentPlayback,
                                );

                            lastAuthoritativePositionRef.current =
                                targetPosition;

                            /*
                             * Participant local pause never survives
                             * a media change.
                             */
                            localPausedRef.current =
                                false;

                            setLocalPaused(false);

                            applyAuthoritativeState(
                                player,
                                targetPosition,
                                currentPlayback.isPlaying,
                                targetPosition >
                                    0,
                            );
                        },

                        onStateChange: (
                            event,
                        ) => {
                            if (
                                generation !==
                                playerGenerationRef.current
                            ) {
                                return;
                            }

                            const YT =
                                window.YT;

                            if (!YT) {
                                return;
                            }

                            /*
                             * -----------------------------------
                             * PAUSED
                             * -----------------------------------
                             */
                            if (
                                event.data ===
                                YT.PlayerState.PAUSED
                            ) {
                                /*
                                 * The YouTube player is now actually
                                 * paused.
                                 */
                                if (
                                    programmaticPauseRef.current
                                ) {
                                    programmaticPauseRef.current =
                                        false;

                                    /*
                                     * If a server-authoritative seek
                                     * had to wait for PAUSED, apply it
                                     * now.
                                     */
                                    if (
                                        localPauseTransitionRef.current
                                    ) {
                                        localPauseTransitionRef.current =
                                            false;

                                        const currentPlayback =
                                            playbackRef.current;

                                        if (
                                            currentPlayback &&
                                            currentPlayback.mediaId ===
                                                mediaRef.current?.mediaId &&
                                            !localPausedRef.current
                                        ) {
                                            const targetPosition =
                                                getAuthoritativePosition(
                                                    currentPlayback,
                                                );

                                            seekLocalPlayer(
                                                player,
                                                targetPosition,
                                            );
                                        }
                                    }

                                    return;
                                }

                                /*
                                 * A programmatic seek can make YouTube
                                 * emit PAUSED even though the shared room
                                 * is still playing.
                                 *
                                 * This is especially important during
                                 * participant RESUME:
                                 *
                                 *   seekTo(...)
                                 *   -> YouTube emits PAUSED
                                 *   -> old logic interpreted that as
                                 *      "participant paused again"
                                 *   -> resume was immediately cancelled.
                                 *
                                 * Consume that callback instead of
                                 * treating it as a user pause.
                                 */
                                if (
                                    programmaticSeekRef.current
                                ) {
                                    programmaticSeekRef.current =
                                        false;

                                    const currentPlayback =
                                        playbackRef.current;

                                    if (
                                        !isHostRef.current &&
                                        !localPausedRef.current &&
                                        currentPlayback?.isPlaying
                                    ) {
                                        /*
                                         * The participant is resuming
                                         * locally. If YouTube left the
                                         * player paused after seekTo(),
                                         * explicitly continue playback.
                                         */
                                        playLocalPlayer(player);
                                    }

                                    return;
                                }

                                /*
                                 * Participant intentionally paused
                                 * locally.
                                 *
                                 * The authoritative server is still
                                 * playing, so this is NOT a shared pause.
                                 */
                                if (
                                    !isHostRef.current &&
                                    playbackRef.current?.isPlaying
                                ) {
                                    localPausedRef.current =
                                        true;

                                    clientSyncStateRef.current =
                                        "locally_paused";

                                    setLocalPaused(true);

                                    return;
                                }

                                /*
                                 * Host native pause.
                                 *
                                 * Only report it if the server still
                                 * says the room is playing.
                                 */
                                if (
                                    isHostRef.current &&
                                    playbackRef.current?.isPlaying
                                ) {
                                    onPauseRef.current();
                                }

                                return;
                            }

                            /*
                             * -----------------------------------
                             * PLAYING
                             * -----------------------------------
                             */
                            if (
                                event.data ===
                                YT.PlayerState.PLAYING
                            ) {
                                /*
                                 * Ignore the PLAYING callback caused
                                 * by our own programmatic play.
                                 */
                                if (
                                    programmaticPlayRef.current
                                ) {
                                    programmaticPlayRef.current =
                                        false;

                                    return;
                                }

                                /*
                                 * Participant is locally paused.
                                 *
                                 * Never allow an unexpected YouTube
                                 * PLAYING event to escape the local
                                 * pause override.
                                 */
                                if (
                                    !isHostRef.current &&
                                    localPausedRef.current
                                ) {
                                    pauseLocalPlayer(
                                        player,
                                    );

                                    return;
                                }

                                /*
                                 * Participant unexpectedly started
                                 * while server says paused.
                                 *
                                 * Stop it locally. DO NOT emit
                                 * video:play because only the host
                                 * can start shared playback.
                                 */
                                if (
                                    !isHostRef.current &&
                                    !playbackRef.current?.isPlaying
                                ) {
                                    pauseLocalPlayer(
                                        player,
                                    );

                                    return;
                                }

                                /*
                                 * Host native Play.
                                 *
                                 * Only report it if the server still
                                 * says the room is paused.
                                 */
                                if (
                                    isHostRef.current &&
                                    !playbackRef.current?.isPlaying
                                ) {
                                    onPlayRef.current();
                                }

                                return;
                            }

                            /*
                             * -----------------------------------
                             * ENDED
                             * -----------------------------------
                             */
                            if (
                                event.data ===
                                YT.PlayerState.ENDED
                            ) {
                                clientSyncStateRef.current =
                                    "following";

                                localPausedRef.current =
                                    false;

                                localPauseTransitionRef.current =
                                    false;

                                setLocalPaused(false);

                                if (
                                    isHostRef.current
                                ) {
                                    onEndedRef.current();
                                }

                                return;
                            }

                            /*
                             * -----------------------------------
                             * BUFFERING
                             * -----------------------------------
                             *
                             * Do not modify synchronization state.
                             */
                        },
                    },
                },
            );

        if (
            isUsablePlayer(player) &&
            generation ===
                playerGenerationRef.current
        ) {
            playerRef.current = player;
        }

        return () => {
            if (
                generation !==
                playerGenerationRef.current
            ) {
                return;
            }

            playerGenerationRef.current += 1;

            const activePlayer =
                playerRef.current;

            playerRef.current = null;

            if (activePlayer) {
                try {
                    activePlayer.destroy();
                } catch {
                    // Ignore cleanup errors.
                }
            }
        };
    }, [apiReady, media?.mediaId, isHost]);

    /*
     * ---------------------------------------------------------
     * AUTHORITATIVE PLAYBACK UPDATES
     * ---------------------------------------------------------
     *
     * IMPORTANT:
     *
     * Even while locallyPaused:
     *
     * playbackRef.current continues to receive the latest
     * authoritative server state.
     *
     * The only thing we suppress is automatic local playback.
     */
    useEffect(() => {
        if (
            !playback ||
            !media ||
            playback.mediaId !==
                media.mediaId
        ) {
            return;
        }

        /*
         * Always remember the latest authoritative position.
         */
        const targetPosition =
            getAuthoritativePosition(playback);

        lastAuthoritativePositionRef.current =
            targetPosition;

        const player =
            playerRef.current;

        if (
            !isUsablePlayer(player)
        ) {
            return;
        }

        /*
         * PARTICIPANT LOCAL PAUSE:
         *
         * Do NOT apply the server playback state to the local
         * YouTube player.
         *
         * But playbackRef has already been updated above.
         *
         * Therefore the participant continues tracking the room
         * timeline while remaining locally paused.
         */
        if (
            !isHostRef.current &&
            localPausedRef.current
        ) {
            return;
        }

        /*
         * If this was a participant resume, we are no longer
         * locally paused.
         */
        const forceSeek =
            clientSyncStateRef.current ===
            "resyncing";

        applyAuthoritativeState(
            player,
            targetPosition,
            playback.isPlaying,
            forceSeek,
        );

        clientSyncStateRef.current =
            "following";
    }, [playback, media?.mediaId]);

    /*
     * ---------------------------------------------------------
     * DRIFT CORRECTION + HOST SEEK DETECTION
     * ---------------------------------------------------------
     *
     * PARTICIPANTS:
     * follow the authoritative timeline unless locally paused.
     *
     * HOST:
     * detect genuine local seeks and report them.
     *
     * IMPORTANT:
     * Host seek detection works both while PLAYING and PAUSED.
     */
    useEffect(() => {
        const interval =
            window.setInterval(() => {
                const player =
                    playerRef.current;

                const currentPlayback =
                    playbackRef.current;

                const currentMedia =
                    mediaRef.current;

                if (
                    !isUsablePlayer(player) ||
                    !currentPlayback ||
                    !currentMedia
                ) {
                    return;
                }

                if (
                    currentPlayback.mediaId !==
                    currentMedia.mediaId
                ) {
                    return;
                }

                let localPosition: number;

                try {
                    localPosition =
                        player.getCurrentTime();
                } catch {
                    return;
                }

                if (
                    !Number.isFinite(
                        localPosition,
                    )
                ) {
                    return;
                }

                /*
                 * -----------------------------------------------
                 * PARTICIPANT
                 * -----------------------------------------------
                 */
                if (
                    !isHostRef.current
                ) {
                    /*
                     * A locally paused participant does NOT move
                     * their player to follow the server.
                     *
                     * Their playbackRef is still current.
                     */
                    if (
                        localPausedRef.current
                    ) {
                        return;
                    }

                    if (
                        !currentPlayback.isPlaying
                    ) {
                        return;
                    }

                    if (
                        clientSyncStateRef.current !==
                        "following"
                    ) {
                        return;
                    }

                    const targetPosition =
                        getAuthoritativePosition(
                            currentPlayback,
                        );

                    const drift =
                        Math.abs(
                            localPosition -
                                targetPosition,
                        );

                    if (
                        drift >
                        SEEK_THRESHOLD_SECONDS
                    ) {
                        seekLocalPlayer(
                            player,
                            targetPosition,
                        );
                    }

                    return;
                }

                /*
                 * -----------------------------------------------
                 * HOST
                 * -----------------------------------------------
                 *
                 * Host is the source of the timeline.
                 *
                 * We NEVER correct the host's player toward the
                 * server.
                 *
                 * Instead, meaningful divergence means the host
                 * manually sought.
                 */
                const targetPosition =
                    getAuthoritativePosition(
                        currentPlayback,
                    );

                const drift =
                    Math.abs(
                        localPosition -
                            targetPosition,
                    );

                /*
                 * Ignore our own programmatic seek.
                 */
                if (
                    programmaticSeekRef.current
                ) {
                    programmaticSeekRef.current =
                        false;

                    lastReportedSeekRef.current =
                        localPosition;

                    return;
                }

                /*
                 * If the server has already acknowledged this
                 * position, it is not a new host seek.
                 */
                const lastAuthoritative =
                    lastAuthoritativePositionRef.current;

                if (
                    lastAuthoritative !== null &&
                    Math.abs(
                        localPosition -
                            lastAuthoritative,
                    ) <=
                        SEEK_THRESHOLD_SECONDS
                ) {
                    lastReportedSeekRef.current =
                        null;

                    return;
                }

                /*
                 * Meaningful divergence = host seek.
                 *
                 * This works whether the room is currently
                 * playing OR paused.
                 */
                if (
                    drift >
                    SEEK_THRESHOLD_SECONDS
                ) {
                    if (
                        lastReportedSeekRef.current ===
                            null ||
                        Math.abs(
                            localPosition -
                                lastReportedSeekRef.current,
                        ) >
                            0.75
                    ) {
                        lastReportedSeekRef.current =
                            localPosition;

                        onSeekRef.current(
                            localPosition,
                        );
                    }

                    return;
                }

                /*
                 * Drift is back within tolerance.
                 * Allow a future seek to be detected.
                 */
                lastReportedSeekRef.current =
                    null;
            }, SYNC_INTERVAL_MS);

        return () => {
            window.clearInterval(interval);
        };
    }, []);

    /*
     * ---------------------------------------------------------
     * PARTICIPANT LOCAL PAUSE / RESUME
     * ---------------------------------------------------------
     */

    function handleParticipantTogglePause() {
        const player =
            playerRef.current;

        if (!isUsablePlayer(player)) {
            return;
        }

        /*
         * -------------------------------------------------------
         * RESUME
         * -------------------------------------------------------
         *
         * Resume is LOCAL.
         *
         * We use the latest authoritative playbackRef that has
         * been continuously maintained even while locally paused.
         *
         * We do NOT call onPlay().
         *
         * Therefore this never emits shared video:play.
         */
        if (localPausedRef.current) {
            const currentPlayback =
                playbackRef.current;

            const currentMedia =
                mediaRef.current;

            if (
                !currentPlayback ||
                !currentMedia ||
                currentPlayback.mediaId !==
                    currentMedia.mediaId
            ) {
                return;
            }

            /*
             * If the room is currently paused, the participant
             * should remain paused rather than independently
             * starting playback.
             */
            if (
                !currentPlayback.isPlaying
            ) {
                const targetPosition =
                    getAuthoritativePosition(
                        currentPlayback,
                    );

                seekLocalPlayer(
                    player,
                    targetPosition,
                );

                localPausedRef.current =
                    true;

                clientSyncStateRef.current =
                    "locally_paused";

                setLocalPaused(true);

                return;
            }

            /*
             * The room is playing.
             *
             * Resync to the latest authoritative position first.
             */
            const targetPosition =
                getAuthoritativePosition(
                    currentPlayback,
                );

            localPausedRef.current = false;

            clientSyncStateRef.current =
                "following";

            setLocalPaused(false);

            /*
             * Explicit local resync.
             *
             * This is intentionally direct and does NOT emit
             * shared video:play.
             */
            seekLocalPlayer(
                player,
                targetPosition,
            );

            playLocalPlayer(player);

            return;
        }

        /*
         * -------------------------------------------------------
         * LOCAL PAUSE
         * -------------------------------------------------------
         *
         * Pause only this participant's local player.
         *
         * NEVER call onPause().
         */
        localPausedRef.current = true;

        clientSyncStateRef.current =
            "locally_paused";

        setLocalPaused(true);

        pauseLocalPlayer(player);
    }

    if (!media) {
        return (
            <div className="flex aspect-video w-full items-center justify-center rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] text-sm text-[var(--color-text-muted)]">
                No video selected
            </div>
        );
    }

    const currentMode =
        playback?.mode ?? "normal";

    const CurrentModeIcon =
        PLAYBACK_MODES.find(
            (m) => m.value === currentMode,
        )?.Icon ?? ListMusic;

    return (
        <div className="flex w-full flex-col gap-2 lg:h-full lg:max-w-4xl lg:justify-center">
            <div className="overflow-hidden rounded-2xl border border-[var(--color-border)] bg-black lg:flex lg:min-h-0 lg:flex-1 lg:items-center lg:justify-center">
                <div
                    ref={containerRef}
                    className="aspect-video w-full lg:h-full lg:w-auto lg:max-w-full"
                />
            </div>

            {isHost && (
                <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2">
                    <div className="flex items-center gap-1.5">
                        <IconButton
                            variant="outline"
                            size="sm"
                            onClick={onPrevious}
                            aria-label="Previous video"
                        >
                            <SkipBack size={15} />
                        </IconButton>

                        <IconButton
                            variant="solid"
                            size="sm"
                            onClick={() => {
                                if (
                                    playback?.isPlaying
                                ) {
                                    onPause();
                                } else {
                                    onPlay();
                                }
                            }}
                            aria-label={
                                playback?.isPlaying
                                    ? "Pause"
                                    : "Play"
                            }
                        >
                            {playback?.isPlaying ? (
                                <Pause
                                    size={15}
                                    fill="currentColor"
                                />
                            ) : (
                                <Play
                                    size={15}
                                    fill="currentColor"
                                    className="ml-0.5"
                                />
                            )}
                        </IconButton>

                        <IconButton
                            variant="outline"
                            size="sm"
                            onClick={onNext}
                            aria-label="Next video"
                        >
                            <SkipForward size={15} />
                        </IconButton>
                    </div>

                    <label className="flex items-center gap-1.5 text-xs text-[var(--color-text-muted)]">
                        <CurrentModeIcon
                            size={13}
                            className="text-[var(--color-text-faint)]"
                        />

                        <select
                            value={currentMode}
                            onChange={(event) => {
                                onSetMode(
                                    event.target
                                        .value as PlaybackMode,
                                );
                            }}
                            aria-label="Playback mode"
                            className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-2)] px-2 py-1.5 text-xs text-[var(--color-text)] outline-none"
                        >
                            {PLAYBACK_MODES.map(
                                (mode) => (
                                    <option
                                        key={
                                            mode.value
                                        }
                                        value={
                                            mode.value
                                        }
                                    >
                                        {mode.label}
                                    </option>
                                ),
                            )}
                        </select>
                    </label>
                </div>
            )}

            {!isHost && (
                <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2">
                    <button
                        type="button"
                        onClick={
                            handleParticipantTogglePause
                        }
                        className="flex items-center gap-1.5 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-2)] px-3 py-1.5 text-xs font-medium text-[var(--color-text)] transition-colors duration-200 hover:border-[var(--color-border-strong)] hover:bg-[var(--color-surface-3)]"
                    >
                        {localPaused ? (
                            <Play
                                size={13}
                                fill="currentColor"
                            />
                        ) : (
                            <Pause
                                size={13}
                                fill="currentColor"
                            />
                        )}

                        {localPaused
                            ? "Resume"
                            : "Pause for me"}
                    </button>

                    <span className="text-[11px] text-[var(--color-text-faint)]">
                        Host controls playback for everyone
                    </span>
                </div>
            )}
        </div>
    );
}